name: ci

on:
  push:
    branches: main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      - name: Build image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          load: true
          build-args: |
            BUILDKIT_INLINE_CACHE=1
          tags: ghcr.io/anapsix/geminabox:latest
      - name: Push image
        run: docker push ghcr.io/anapsix/geminabox:latest
